name: Combine Actiones

on:
  workflow_dispatch:
    inputs:
      parameter1:
        description: 'First parameter'
        type: string
        default: "abc  "
      parameter2:
        description: 'Second parameter'
        type: string
        default: "def "
       
    
jobs:
  combine:
    uses: ashwinjamescloud/ashwin1/.github/workflows/reusable.yml@main
    with:
      param1: ${{inputs.parameter1}}
      param2: ${{inputs.parameter2}}
  printoutput:
      name: Combine Parameters
      runs-on: ubuntu-latest 
      steps:
        - run: echo ' ${{ workflow_call.outputs }}'
        
        
    
        
